import { Nutrition } from '../types/foodstuff'

export const emptyNutrition: Nutrition = {
  energy_kcal: 0,
  protein: 0,
  fat: 0,
  carbohydrate: 0,
  vitamin_a: 0,
  vitamin_d: 0,
  vitamin_e: 0,
  vitamin_k: 0,
  vitamin_b1: 0,
  vitamin_b2: 0,
  niacin: 0,
  vitamin_b6: 0,
  vitamin_b12: 0,
  folic_acid: 0,
  pantothenic_acid: 0,
  vitamin_c: 0,
  k: 0,
  ca: 0,
  mg: 0,
  phosphorus: 0,
  iron: 0,
  zn: 0,
  copper: 0,
  mn: 0,
  salt: 0,
}
